#pragma config(Motor,  port1,           flWheel,       tmotorVex393TurboSpeed_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           blWheel,       tmotorVex393TurboSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           lLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           tlCat,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           blCat,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           brCat,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           trCat,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rLift,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           brWheel,       tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          frWheel,       tmotorVex393TurboSpeed_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setRDrive(int pwr) {
	motor[frWheel] =
		motor[brWheel] =
		pwr;
}

void setLDrive(int pwr) {
	motor[flWheel] =
		motor[blWheel] =
		pwr;
}

void arcCtl(int move, int rot) {
	setLDrive(move + rot);
	setRDrive(move - rot);
}

void setLift(int pwr) {
	motor[lLift] =
		motor[rLift] =
		pwr;
}

void setCat(int pwr) {
	motor[tlCat] =
		motor[blCat] =
		motor[trCat] =
		motor[brCat] =
		pwr;
}

task main()
{
	int sticks[4],
		catPwr;
	bool cubCtl;
	word cubBtn;
	while(1) {
		for(int i = 0; i < 4; i++) {
			sticks[i] = (fabs(vexRT[i]) >= 7)
				? vexRT[i]
				: 0;
		}

		if(!vexRT[Btn7U] && cubBtn)
			cubCtl = !cubCtl;
		cubBtn = vexRT[Btn7U];

		if(cubCtl)
			arcCtl(pow(sticks[2], 3), pow(sticks[0], 3));
		else
			arcCtl(sticks[2], sticks[0]);

		setLift(
			(vexRT[Btn5U]
				^ vexRT[Btn5D])
				? (vexRT[Btn5U]
					? 127
					: -127)
				: 0);

		//This calculation will change later
				//First we need to figure out
				//Catapult control & protection
		catPwr = (vexRT[Btn6U] ^ vexRT[Btn6D])
			? (vexRT[Btn6U]
				? 127
				: -127)
			: 0;

		setCat(catPwr);

	}
}
